I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 425, in script
    prepodone "Так. Всем здравствуйте! Сегодня начинается курс лекций по разработке мобильных приложений."
Exception: Sayer 'prepodone' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 425, in script
    prepodone "Так. Всем здравствуйте! Сегодня начинается курс лекций по разработке мобильных приложений."
  File "C:\Users\user\Desktop\новелла\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\user\Desktop\новелла\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'prepodone' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
The game of life 1.0
Thu Nov 16 02:12:39 2023
